# Generated by Django 3.0 on 2024-04-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=128)),
                ('status', models.CharField(default='A', max_length=1)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_confirmacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
